### ISSUE TITLE
iSponsorBlockTV add-on not working

### ISSUE THREAD

**Issue by Gmarapet** [bertybuttface/addons#32] opened 2024-08-09 11:32 UTC
iSponsorBlockTV add-on
Current version: 2.1.0

When Add-on starting Home Assitant see it working but on TV (Samsung Tizen) YouTube ads is not affected at all.
If I run dmunozv04/iSponsorBlockTV on docker with ssh on machine where a Home Assistant is installed, ads on TV start muting and skipping, but supervisor reports unhealthy environment, so i can't use it in that way. Please help me to fix that issue.

Log information from add-on:
When add-on is starting

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun isponsorblocktv (no readiness notification)
s6-rc: info: service legacy-services successfully started
[14:28:30] INFO: Starting...
2024-08-09 14:28:31,808 - iSponsorBlockTV-MY-SCREEN-ID - INFO - Starting device
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f966d4fb0>
```

When it is stopping.

```
s6-rc: info: service legacy-services: stopping
[11:30:57] INFO: Service restart after closing
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by bertybuttface** [comment] 2024-10-21 12:03
Can't reproduce with latest version, closing for now. Feel free to reopen it if you continue having problems.

**Closed as completed by bertybuttface** 2024-10-21 12:03 UTC
